import { createSQLiteThread } from 'sqlite-wasm-http';
import type { BaseIngredient, Portion, ICatalogProvider } from '@quomida/domain-core';
import { DatabaseBootstrapper } from './DatabaseBootstrapper.js';

// Dynamically load built-in system catalog metadata if generated by the ETL pipeline
const metaModules = import.meta.glob<{ default?: { itemCount?: number }; itemCount?: number }>(
  '../generated/system_meta.json',
  { eager: true }
);
const metaEntry = (Object.values(metaModules)[0] || {}) as any;
export const SYSTEM_CATALOG_ITEM_COUNT: number =
  metaEntry?.itemCount ?? metaEntry?.default?.itemCount ?? 0;
export const SYSTEM_CATALOG_META = {
  itemCount: SYSTEM_CATALOG_ITEM_COUNT,
  ingredientsCount: metaEntry?.ingredientsCount ?? metaEntry?.default?.ingredientsCount ?? 0,
  portionsCount: metaEntry?.portionsCount ?? metaEntry?.default?.portionsCount ?? 0,
  generatedAt: metaEntry?.generatedAt ?? metaEntry?.default?.generatedAt ?? '',
  catalogVersion: metaEntry?.catalogVersion ?? metaEntry?.default?.catalogVersion ?? '',
};

export function isCrossOriginIsolated(): boolean {
  if (typeof SharedArrayBuffer === 'undefined') return false;
  const target = typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : null);
  if (target && 'crossOriginIsolated' in target) {
    return Boolean((target as any).crossOriginIsolated);
  }
  return true;
}

export class RemoteCatalogService implements ICatalogProvider {
  public static readonly CATALOG_DOWNLOADED_EVENT = 'quomida:catalog-downloaded';
  private static listeners = new Set<() => void>();

  public static onCatalogDownloaded(listener: () => void): () => void {
    RemoteCatalogService.listeners.add(listener);
    return () => RemoteCatalogService.listeners.delete(listener);
  }

  public static clearListeners(): void {
    RemoteCatalogService.listeners.clear();
  }

  private static instance: RemoteCatalogService | null = null;

  public static getInstance(_baseUrl?: string): RemoteCatalogService {
    if (!RemoteCatalogService.instance) {
      RemoteCatalogService.instance = new RemoteCatalogService();
    }
    return RemoteCatalogService.instance;
  }

  public static resetInstance(): void {
    if (RemoteCatalogService.instance) {
      RemoteCatalogService.instance.destroy();
      RemoteCatalogService.instance = null;
    }
  }

  public static notifyCatalogDownloaded(): void {
    const target = typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : null);
    if (target && typeof (target as any).dispatchEvent === 'function') {
      try {
        const event = typeof CustomEvent !== 'undefined'
          ? new CustomEvent(RemoteCatalogService.CATALOG_DOWNLOADED_EVENT)
          : { type: RemoteCatalogService.CATALOG_DOWNLOADED_EVENT };
        (target as any).dispatchEvent(event);
      } catch {}
    }

    RemoteCatalogService.listeners.forEach((listener) => {
      try {
        listener();
      } catch (err) {
        console.warn('[RemoteCatalogService] Error in download listener:', err);
      }
    });
  }

  private workerPromise: Promise<any> | null = null;
  private initPromise: Promise<void> | null = null;
  private totalLoadedItems = 0;
  private removeStaticListener: (() => void) | null = null;

  private onCatalogDownloadedHandler = () => {
    this.reset().catch((err) => {
      console.warn('[RemoteCatalogService] Error resetting worker after catalog download:', err);
    });
  };

  constructor(_baseUrl?: string) {
    this.removeStaticListener = RemoteCatalogService.onCatalogDownloaded(this.onCatalogDownloadedHandler);

    const target = typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : null);
    if (target && typeof (target as any).addEventListener === 'function') {
      try {
        (target as any).addEventListener(RemoteCatalogService.CATALOG_DOWNLOADED_EVENT, this.onCatalogDownloadedHandler);
      } catch {}
    }
  }

  get isFullCatalogLoaded(): boolean {
    return this.totalLoadedItems > (SYSTEM_CATALOG_META.itemCount || 0);
  }

  get itemCount(): number {
    return this.totalLoadedItems;
  }

  public async reset(): Promise<void> {
    this.initPromise = null;
    const wp = this.workerPromise;
    this.workerPromise = null;

    if (wp) {
      try {
        const worker = await wp;
        await worker('close', {});
      } catch {
        // Ignore close error
      }
    }
  }

  public destroy(): void {
    if (this.removeStaticListener) {
      this.removeStaticListener();
      this.removeStaticListener = null;
    }
    const target = typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : null);
    if (target && typeof (target as any).removeEventListener === 'function') {
      try {
        (target as any).removeEventListener(RemoteCatalogService.CATALOG_DOWNLOADED_EVENT, this.onCatalogDownloadedHandler);
      } catch {}
    }
    this.reset().catch(() => {});
  }

  private async ensureInitialized(): Promise<void> {
    if (!this.initPromise) {
      this.initPromise = this.doInitialize();
    }
    return this.initPromise;
  }

  private async doInitialize(): Promise<void> {
    try {
      // 1. Ensure OPFS has been bootstrapped with system.sqlite if needed
      await DatabaseBootstrapper.ensureSystemCatalogOPFS().catch((err) => {
        console.warn('[RemoteCatalogService] ensureSystemCatalogOPFS notice:', err);
      });

      // 2. Open dedicated local SQLite worker
      const worker = await createSQLiteThread();
      let localTotal = 0;
      let opfsOpened = false;

      const hasIsolation = isCrossOriginIsolated();

      if (hasIsolation) {
        try {
          await worker('open', { filename: 'catalog.sqlite', vfs: 'opfs' });
          const countRes = await worker('exec', { 
            sql: 'SELECT (SELECT count(*) FROM base_ingredients) + (SELECT count(*) FROM portions)', 
            rowMode: 'array' 
          } as any);
          localTotal = (countRes as any)?.result?.resultRows?.[0]?.[0] || 0;
          if (localTotal > 0) {
            opfsOpened = true;
          }
        } catch (opfsErr) {
          console.warn('[RemoteCatalogService] OPFS mount via vfs:opfs unavailable, falling back to zero-header loading:', opfsErr);
        }
      }

      // If OPFS was not opened (zero-header mode without COOP/COEP, or OPFS not yet seeded):
      if (!opfsOpened) {
        let catalogBytes: Uint8Array | null = null;

        // Try reading existing catalog.sqlite from OPFS (standard FileSystem API requires zero headers)
        if (typeof navigator !== 'undefined' && navigator.storage) {
          try {
            const root = await navigator.storage.getDirectory();
            const handle = await root.getFileHandle('catalog.sqlite');
            const file = await handle.getFile();
            if (file.size > 0) {
              const buffer = await file.arrayBuffer();
              catalogBytes = new Uint8Array(buffer);
            }
          } catch {
            // Not in OPFS yet
          }
        }

        // If not in OPFS, fetch the static /system.sqlite (240 KB built-in catalog)
        if (!catalogBytes) {
          try {
            const res = await fetch('/system.sqlite');
            if (res.ok) {
              const buffer = await res.arrayBuffer();
              catalogBytes = new Uint8Array(buffer);
            }
          } catch (fetchErr) {
            console.warn('[RemoteCatalogService] Failed to fetch /system.sqlite:', fetchErr);
          }
        }

        if (catalogBytes) {
          try {
            await (worker as any)('open', { filename: 'catalog.sqlite', byteArray: catalogBytes });
            const countRes = await worker('exec', { 
              sql: 'SELECT (SELECT count(*) FROM base_ingredients) + (SELECT count(*) FROM portions)', 
              rowMode: 'array' 
            } as any);
            localTotal = (countRes as any)?.result?.resultRows?.[0]?.[0] || 0;
            console.log(`[RemoteCatalogService] Initialized local catalog with ${localTotal} items.`);
          } catch (memErr) {
            console.warn('[RemoteCatalogService] Failed to load catalog via byteArray:', memErr);
          }
        }
      }

      this.totalLoadedItems = localTotal;
      this.workerPromise = Promise.resolve(worker);
    } catch (err) {
      this.initPromise = null;
      throw err;
    }
  }

  private async getWorker() {
    await this.ensureInitialized();
    if (!this.workerPromise) {
      throw new Error('Local SQLite worker is not initialized.');
    }
    return this.workerPromise;
  }

  async searchIngredients(query: string, limit: number = 20): Promise<BaseIngredient[]> {
    const sanitizedQuery = query.replace(/[^\w\s\u00C0-\u017F]/g, '');
    const matchQuery = sanitizedQuery.split(/\s+/).filter(Boolean).map(term => term + '*').join(' ');
    
    if (!matchQuery) return [];

    const worker = await this.getWorker();

    // 1. Try FTS5 query (fastest, typo-tolerant trigram/prefix)
    const ftsSql = `
      SELECT 
        b.id as id,
        b.name as name,
        b.source as source,
        b.lang as lang,
        b.calories_100g as calories_100g,
        b.protein_100g as protein_100g,
        b.carbs_100g as carbs_100g,
        b.fats_100g as fats_100g,
        b.contentHash as contentHash
      FROM base_ingredients b
      JOIN base_ingredients_fts f ON b.id = f.id 
      WHERE f.base_ingredients_fts MATCH '${matchQuery.replace(/'/g, "''")}'
      LIMIT ${limit}
    `;

    try {
      const res = await worker('exec', { sql: ftsSql, rowMode: 'array' } as any);
      const rows = res?.result?.resultRows || [];
      if (rows.length > 0) {
        return this.mapRowsToIngredients(rows);
      }
    } catch (e) {
      console.warn('[RemoteCatalogService] FTS query error, falling back to LIKE:', e);
    }

    // 2. Fallback to LIKE substring query on local database
    const likeSql = `
      SELECT 
        b.id as id,
        b.name as name,
        b.source as source,
        b.lang as lang,
        b.calories_100g as calories_100g,
        b.protein_100g as protein_100g,
        b.carbs_100g as carbs_100g,
        b.fats_100g as fats_100g,
        b.contentHash as contentHash
      FROM base_ingredients b
      WHERE name LIKE '%${sanitizedQuery.replace(/'/g, "''")}%'
      LIMIT ${limit}
    `;

    try {
      const res = await worker('exec', { sql: likeSql, rowMode: 'array' } as any);
      return this.mapRowsToIngredients(res?.result?.resultRows || []);
    } catch {
      return [];
    }
  }

  async getPortionsForIngredient(baseFoodId: string): Promise<Portion[]> {
    const worker = await this.getWorker();
    const sql = `
      SELECT 
        id as id,
        base_food_id as base_food_id,
        name as name,
        equivalent_weight_g as equivalent_weight_g,
        contentHash as contentHash
      FROM portions 
      WHERE base_food_id = '${baseFoodId.replace(/'/g, "''")}'
    `;

    try {
      const res = await worker('exec', { sql, rowMode: 'array' } as any);
      const rows = res?.result?.resultRows || [];
      return this.mapRowsToPortions(rows);
    } catch (e) {
      console.warn('[RemoteCatalogService] Portions query error:', e);
      return [];
    }
  }

  private mapRowsToIngredients(rows: any[][]): BaseIngredient[] {
    return rows.map((vals: any) => ({
      id: vals[0],
      name: vals[1],
      source: vals[2],
      lang: vals[3],
      calories_100g: vals[4],
      protein_100g: vals[5],
      carbs_100g: vals[6],
      fats_100g: vals[7],
      contentHash: vals[8]
    })) as BaseIngredient[];
  }

  private mapRowsToPortions(rows: any[][]): Portion[] {
    return rows.map((vals: any) => ({
      id: vals[0],
      base_food_id: vals[1],
      name: vals[2],
      equivalent_weight_g: vals[3],
      contentHash: vals[4]
    })) as Portion[];
  }
}
