import { createSQLiteThread, createHttpBackend } from 'sqlite-wasm-http';
import type { BaseIngredient, Portion, ICatalogProvider } from '@quomida/domain-core';
import { DatabaseBootstrapper } from './DatabaseBootstrapper.js';

// Dynamically load built-in system catalog metadata if generated by the ETL pipeline
const metaModules = import.meta.glob<{ default?: { itemCount?: number }; itemCount?: number }>(
  '../generated/system_meta.json',
  { eager: true }
);
const metaEntry = (Object.values(metaModules)[0] || {}) as any;
export const SYSTEM_CATALOG_ITEM_COUNT: number =
  metaEntry?.itemCount ?? metaEntry?.default?.itemCount ?? 0;
export const SYSTEM_CATALOG_META = {
  itemCount: SYSTEM_CATALOG_ITEM_COUNT,
  ingredientsCount: metaEntry?.ingredientsCount ?? metaEntry?.default?.ingredientsCount ?? 0,
  portionsCount: metaEntry?.portionsCount ?? metaEntry?.default?.portionsCount ?? 0,
  generatedAt: metaEntry?.generatedAt ?? metaEntry?.default?.generatedAt ?? '',
  catalogVersion: metaEntry?.catalogVersion ?? metaEntry?.default?.catalogVersion ?? '',
};

export class RemoteCatalogService implements ICatalogProvider {
  public static readonly CATALOG_DOWNLOADED_EVENT = 'quomida:catalog-downloaded';
  private static listeners = new Set<() => void>();

  public static onCatalogDownloaded(listener: () => void): () => void {
    RemoteCatalogService.listeners.add(listener);
    return () => RemoteCatalogService.listeners.delete(listener);
  }

  public static clearListeners(): void {
    RemoteCatalogService.listeners.clear();
  }

  private static instance: RemoteCatalogService | null = null;

  public static getInstance(baseUrl?: string): RemoteCatalogService {
    if (!RemoteCatalogService.instance) {
      const url = baseUrl !== undefined
        ? baseUrl
        : ((typeof import.meta !== 'undefined' && import.meta.env?.VITE_CATALOG_BASE_URL) || '');
      RemoteCatalogService.instance = new RemoteCatalogService(url);
    }
    return RemoteCatalogService.instance;
  }

  public static resetInstance(): void {
    if (RemoteCatalogService.instance) {
      RemoteCatalogService.instance.destroy();
      RemoteCatalogService.instance = null;
    }
  }

  public static notifyCatalogDownloaded(): void {
    // 1. Dispatch custom event on window if in DOM
    const target = typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : null);
    if (target && typeof (target as any).dispatchEvent === 'function') {
      try {
        const event = typeof CustomEvent !== 'undefined'
          ? new CustomEvent(RemoteCatalogService.CATALOG_DOWNLOADED_EVENT)
          : { type: RemoteCatalogService.CATALOG_DOWNLOADED_EVENT };
        (target as any).dispatchEvent(event);
      } catch {}
    }

    // 2. Directly notify all registered active listeners
    RemoteCatalogService.listeners.forEach((listener) => {
      try {
        listener();
      } catch (err) {
        console.warn('[RemoteCatalogService] Error in download listener:', err);
      }
    });
  }

  private localWorkerPromise: Promise<any> | null = null;
  private remoteWorkerPromise: Promise<any> | null = null;
  private initPromise: Promise<void> | null = null;

  private isUsingHttpFallback = false;
  private hasRemoteFailedState = false;
  private remoteCooldownUntil = 0;

  private baseUrl: string;
  private catalogUrl: string;
  private metaUrl: string;
  private removeStaticListener: (() => void) | null = null;
  private onlineListener: (() => void) | null = null;
  private offlineListener: (() => void) | null = null;

  private onCatalogDownloadedHandler = () => {
    this.reset().catch((err) => {
      console.warn('[RemoteCatalogService] Error resetting worker after catalog download:', err);
    });
  };

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl.replace(/\/+$/, '');
    this.catalogUrl = this.baseUrl ? `${this.baseUrl}/catalog.sqlite` : '/catalog.sqlite';
    this.metaUrl = this.baseUrl ? `${this.baseUrl}/catalog_meta.json` : '/catalog_meta.json';

    this.removeStaticListener = RemoteCatalogService.onCatalogDownloaded(this.onCatalogDownloadedHandler);

    const target = typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : null);
    if (target && typeof (target as any).addEventListener === 'function') {
      try {
        (target as any).addEventListener(RemoteCatalogService.CATALOG_DOWNLOADED_EVENT, this.onCatalogDownloadedHandler);
        
        this.onlineListener = () => {
          this.resetCircuitBreaker();
        };
        this.offlineListener = () => {
          this.isUsingHttpFallback = false;
          this.hasRemoteFailedState = false;
        };
        (target as any).addEventListener('online', this.onlineListener);
        (target as any).addEventListener('offline', this.offlineListener);
      } catch {}
    }
  }

  get isHttpFallbackActive(): boolean {
    return this.isUsingHttpFallback;
  }

  get hasRemoteFailed(): boolean {
    return this.hasRemoteFailedState;
  }

  public isCircuitBreakerOpen(): boolean {
    return this.hasRemoteFailedState && Date.now() < this.remoteCooldownUntil;
  }

  public resetCircuitBreaker(): void {
    this.hasRemoteFailedState = false;
    this.remoteCooldownUntil = 0;
  }

  private tripCircuitBreaker(): void {
    this.hasRemoteFailedState = true;
    this.remoteCooldownUntil = Date.now() + 30000; // 30s cooldown
    if (this.remoteWorkerPromise) {
      const oldPromise = this.remoteWorkerPromise;
      this.remoteWorkerPromise = null;
      oldPromise.then(w => w('close', {}).catch(() => {})).catch(() => {});
    }
  }

  public async reset(): Promise<void> {
    this.initPromise = null;
    this.isUsingHttpFallback = false;
    this.hasRemoteFailedState = false;
    this.remoteCooldownUntil = 0;

    const lw = this.localWorkerPromise;
    const rw = this.remoteWorkerPromise;
    this.localWorkerPromise = null;
    this.remoteWorkerPromise = null;

    if (lw) {
      try {
        const worker = await lw;
        await worker('close', {});
      } catch (e) {
        // Ignore close error
      }
    }
    if (rw) {
      try {
        const worker = await rw;
        await worker('close', {});
      } catch (e) {
        // Ignore close error
      }
    }
  }

  public destroy(): void {
    if (this.removeStaticListener) {
      this.removeStaticListener();
      this.removeStaticListener = null;
    }
    const target = typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : null);
    if (target && typeof (target as any).removeEventListener === 'function') {
      try {
        (target as any).removeEventListener(RemoteCatalogService.CATALOG_DOWNLOADED_EVENT, this.onCatalogDownloadedHandler);
        if (this.onlineListener) (target as any).removeEventListener('online', this.onlineListener);
        if (this.offlineListener) (target as any).removeEventListener('offline', this.offlineListener);
      } catch {}
    }
    this.reset().catch(() => {});
  }

  private async ensureInitialized(): Promise<void> {
    if (!this.initPromise) {
      this.initPromise = this.doInitialize();
    }
    return this.initPromise;
  }

  private async doInitialize(): Promise<void> {
    try {
      // 1. Ensure OPFS has been bootstrapped with system.sqlite if needed
      await DatabaseBootstrapper.ensureSystemCatalogOPFS().catch((err) => {
        console.warn('[RemoteCatalogService] ensureSystemCatalogOPFS notice:', err);
      });

      // 2. Open dedicated local SQLite worker for OPFS
      const localWorker = await createSQLiteThread({ 
        http: createHttpBackend({ maxPageSize: 4096 })
      });
      let localTotal = 0;
      try {
        await localWorker('open', { filename: 'catalog.sqlite', vfs: 'opfs' });
        // 3. Query total count in local SQLite (ingredients + portions)
        const countRes = await localWorker('exec', { 
          sql: 'SELECT (SELECT count(*) FROM base_ingredients) + (SELECT count(*) FROM portions)', 
          rowMode: 'array' 
        } as any);
        localTotal = (countRes as any)?.result?.resultRows?.[0]?.[0] || 0;
      } catch (opfsErr) {
        console.warn('[RemoteCatalogService] Could not mount OPFS database (Missing SharedArrayBuffer or COOP/COEP headers):', opfsErr);
        try {
          await localWorker('open', { filename: ':memory:' });
        } catch {}
      }
      this.localWorkerPromise = Promise.resolve(localWorker);

      // 4. Condition to NOT use network is to have the full catalog downloaded locally.
      // If localTotal > SYSTEM_CATALOG_META.itemCount (the built-in catalog count generated at build-time),
      // we know the full external catalog was downloaded and is available locally in OPFS.
      // ZERO network calls needed!
      if (SYSTEM_CATALOG_META.itemCount > 0 && localTotal > SYSTEM_CATALOG_META.itemCount) {
        console.log(`[RemoteCatalogService] Full catalog hydrated locally (${localTotal} items > built-in ${SYSTEM_CATALOG_META.itemCount}). Zero network needed.`);
        this.isUsingHttpFallback = false;
        return;
      }

      const isOnline = typeof navigator === 'undefined' ? true : navigator.onLine;
      let shouldUseHttp = false;

      if (isOnline && this.baseUrl) {
        try {
          const metaRes = await fetch(this.metaUrl, { 
            cache: 'no-cache', 
            signal: typeof AbortSignal !== 'undefined' && 'timeout' in AbortSignal ? AbortSignal.timeout(3000) : undefined 
          });
          if (metaRes.ok) {
            const meta = await metaRes.json();
            const remoteItemCount = Number(meta?.itemCount);
            if (remoteItemCount && localTotal < remoteItemCount) {
              console.log(`[RemoteCatalogService] Local SQLite has ${localTotal} items, remote has ${remoteItemCount}. Using HTTP Range Requests while online.`);
              shouldUseHttp = true;
            } else {
              console.log(`[RemoteCatalogService] Full catalog hydrated locally (${localTotal} items). Zero network needed.`);
            }
          }
        } catch {
          console.log('[RemoteCatalogService] Remote catalog metadata unreachable. Using local OPFS catalog.');
        }
      }

      this.isUsingHttpFallback = shouldUseHttp;
    } catch (err) {
      this.initPromise = null;
      throw err;
    }
  }

  private async getLocalWorker() {
    await this.ensureInitialized();
    if (!this.localWorkerPromise) {
      throw new Error('Local SQLite worker is not initialized.');
    }
    return this.localWorkerPromise;
  }

  private getRemoteWorker(): Promise<any> {
    if (!this.remoteWorkerPromise) {
      this.remoteWorkerPromise = (async () => {
        const worker = await createSQLiteThread({ 
          http: createHttpBackend({ maxPageSize: 4096 })
        });
        await worker('open', { filename: this.catalogUrl, vfs: 'http' });
        return worker;
      })();
    }
    return this.remoteWorkerPromise;
  }

  async searchIngredients(query: string, limit: number = 20): Promise<BaseIngredient[]> {
    const sanitizedQuery = query.replace(/[^\w\s\u00C0-\u017F]/g, '');
    const matchQuery = sanitizedQuery.split(/\s+/).filter(Boolean).map(term => term + '*').join(' ');
    
    if (!matchQuery) return [];

    await this.ensureInitialized();

    // 1. Always query local OPFS catalog first (instant < 5ms)
    let localItems: BaseIngredient[] = [];
    try {
      localItems = await this.queryLocalIngredients(matchQuery, sanitizedQuery, limit);
    } catch (err) {
      console.warn('[RemoteCatalogService] Local search query error:', err);
    }

    // 2. If not using HTTP fallback, return local items immediately
    if (!this.isUsingHttpFallback) {
      this.hasRemoteFailedState = false;
      return localItems;
    }

    // 3. If circuit breaker is open (remote failed recently), return local items immediately
    if (this.isCircuitBreakerOpen()) {
      return localItems;
    }

    // 4. Query remote catalog with responsive 3.5s timeout
    try {
      const remoteItems = await this.queryRemoteIngredients(sanitizedQuery, limit);
      this.hasRemoteFailedState = false;
      // Consolidate: remote items with local items (deduplicated by ID)
      return this.mergeIngredients(remoteItems, localItems, limit);
    } catch (err: any) {
      console.warn('[RemoteCatalogService] Remote search failed, falling back to local results:', err?.message || err);
      this.tripCircuitBreaker();
      // Graceful degradation: return consolidated local results
      return localItems;
    }
  }

  private async queryLocalIngredients(matchQuery: string, sanitizedQuery: string, limit: number): Promise<BaseIngredient[]> {
    const worker = await this.getLocalWorker();

    // 1. Try FTS5 query
    const ftsSql = `
      SELECT 
        b.id as id,
        b.name as name,
        b.source as source,
        b.lang as lang,
        b.calories_100g as calories_100g,
        b.protein_100g as protein_100g,
        b.carbs_100g as carbs_100g,
        b.fats_100g as fats_100g,
        b.contentHash as contentHash
      FROM base_ingredients b
      JOIN base_ingredients_fts f ON b.id = f.id 
      WHERE f.base_ingredients_fts MATCH '${matchQuery.replace(/'/g, "''")}'
      LIMIT ${limit}
    `;

    try {
      const res = await worker('exec', { sql: ftsSql, rowMode: 'array' } as any);
      const rows = res?.result?.resultRows || [];
      if (rows.length > 0) {
        return this.mapRowsToIngredients(rows);
      }
    } catch (e) {
      console.warn('[RemoteCatalogService] Local FTS query error, falling back to LIKE:', e);
    }

    // 2. Fallback to LIKE substring query on local database
    const likeSql = `
      SELECT 
        b.id as id,
        b.name as name,
        b.source as source,
        b.lang as lang,
        b.calories_100g as calories_100g,
        b.protein_100g as protein_100g,
        b.carbs_100g as carbs_100g,
        b.fats_100g as fats_100g,
        b.contentHash as contentHash
      FROM base_ingredients b
      WHERE name LIKE '%${sanitizedQuery.replace(/'/g, "''")}%'
      LIMIT ${limit}
    `;

    try {
      const res = await worker('exec', { sql: likeSql, rowMode: 'array' } as any);
      return this.mapRowsToIngredients(res?.result?.resultRows || []);
    } catch {
      return [];
    }
  }

  private async queryRemoteIngredients(sanitizedQuery: string, limit: number): Promise<BaseIngredient[]> {
    const worker = await this.getRemoteWorker();
    const sql = `
      SELECT 
        b.id as id,
        b.name as name,
        b.source as source,
        b.lang as lang,
        b.calories_100g as calories_100g,
        b.protein_100g as protein_100g,
        b.carbs_100g as carbs_100g,
        b.fats_100g as fats_100g,
        b.contentHash as contentHash
      FROM base_ingredients b
      WHERE name LIKE '%${sanitizedQuery.replace(/'/g, "''")}%'
      LIMIT ${limit}
    `;

    const res = await Promise.race([
      worker('exec', { sql, rowMode: 'array' } as any),
      new Promise<any>((_, reject) => 
        setTimeout(() => reject(new Error('Remote search timeout (3.5s)')), 3500)
      )
    ]);

    const rows = res?.result?.resultRows || [];
    return this.mapRowsToIngredients(rows);
  }

  private mergeIngredients(remote: BaseIngredient[], local: BaseIngredient[], limit: number): BaseIngredient[] {
    const seen = new Set<string>();
    const merged: BaseIngredient[] = [];

    // Prioritize remote enriched results when available
    for (const item of remote) {
      if (!seen.has(item.id)) {
        seen.add(item.id);
        merged.push(item);
      }
    }

    // Append any extra local items not already in remote
    for (const item of local) {
      if (!seen.has(item.id)) {
        seen.add(item.id);
        merged.push(item);
      }
    }

    return merged.slice(0, limit);
  }

  async getPortionsForIngredient(baseFoodId: string): Promise<Portion[]> {
    await this.ensureInitialized();
    const sql = `
      SELECT 
        id as id,
        base_food_id as base_food_id,
        name as name,
        equivalent_weight_g as equivalent_weight_g,
        contentHash as contentHash
      FROM portions 
      WHERE base_food_id = '${baseFoodId.replace(/'/g, "''")}'
    `;

    // 1. Try local OPFS first
    try {
      const localWorker = await this.getLocalWorker();
      const res = await localWorker('exec', { sql, rowMode: 'array' } as any);
      const rows = res?.result?.resultRows || [];
      if (rows.length > 0) {
        return this.mapRowsToPortions(rows);
      }
    } catch (e) {
      console.warn('[RemoteCatalogService] Local portions query error:', e);
    }

    // 2. If not found locally, and using HTTP fallback and circuit breaker not open
    if (!this.isUsingHttpFallback || this.isCircuitBreakerOpen()) {
      return [];
    }

    // 3. Query remote worker with 3.5s timeout
    try {
      const remoteWorker = await this.getRemoteWorker();
      const res = await Promise.race([
        remoteWorker('exec', { sql, rowMode: 'array' } as any),
        new Promise<any>((_, reject) => 
          setTimeout(() => reject(new Error('Remote portions timeout (3.5s)')), 3500)
        )
      ]);
      const rows = res?.result?.resultRows || [];
      return this.mapRowsToPortions(rows);
    } catch (err) {
      console.warn('[RemoteCatalogService] Remote portions failed, returning empty:', err);
      return [];
    }
  }

  private mapRowsToIngredients(rows: any[][]): BaseIngredient[] {
    return rows.map((vals: any) => ({
      id: vals[0],
      name: vals[1],
      source: vals[2],
      lang: vals[3],
      calories_100g: vals[4],
      protein_100g: vals[5],
      carbs_100g: vals[6],
      fats_100g: vals[7],
      contentHash: vals[8]
    })) as BaseIngredient[];
  }

  private mapRowsToPortions(rows: any[][]): Portion[] {
    return rows.map((vals: any) => ({
      id: vals[0],
      base_food_id: vals[1],
      name: vals[2],
      equivalent_weight_g: vals[3],
      contentHash: vals[4]
    })) as Portion[];
  }
}
