import { createSQLiteThread, createHttpBackend } from 'sqlite-wasm-http';
import type { BaseIngredient, Portion, ICatalogProvider } from '@quomida/domain-core';
import { DatabaseBootstrapper } from './DatabaseBootstrapper.js';
// Dynamically load built-in system catalog metadata if generated by the ETL pipeline
const metaModules = (typeof import.meta !== 'undefined' && typeof import.meta.glob === 'function')
  ? import.meta.glob<{ default?: { itemCount?: number }; itemCount?: number }>(
      '../generated/system_meta.json',
      { eager: true }
    )
  : {};
const metaEntry = metaModules['../generated/system_meta.json'] as any;
export const SYSTEM_CATALOG_ITEM_COUNT: number =
  metaEntry?.itemCount ?? metaEntry?.default?.itemCount ?? 0;
export const SYSTEM_CATALOG_META = {
  itemCount: SYSTEM_CATALOG_ITEM_COUNT,
  ingredientsCount: metaEntry?.ingredientsCount ?? metaEntry?.default?.ingredientsCount ?? 0,
  portionsCount: metaEntry?.portionsCount ?? metaEntry?.default?.portionsCount ?? 0,
  generatedAt: metaEntry?.generatedAt ?? metaEntry?.default?.generatedAt ?? '',
  catalogVersion: metaEntry?.catalogVersion ?? metaEntry?.default?.catalogVersion ?? '',
};

export class RemoteCatalogService implements ICatalogProvider {
  public static readonly CATALOG_DOWNLOADED_EVENT = 'quomida:catalog-downloaded';
  private static listeners = new Set<() => void>();

  public static onCatalogDownloaded(listener: () => void): () => void {
    RemoteCatalogService.listeners.add(listener);
    return () => RemoteCatalogService.listeners.delete(listener);
  }

  public static clearListeners(): void {
    RemoteCatalogService.listeners.clear();
  }

  private static instance: RemoteCatalogService | null = null;

  public static getInstance(baseUrl?: string): RemoteCatalogService {
    if (!RemoteCatalogService.instance) {
      const url = baseUrl !== undefined
        ? baseUrl
        : ((typeof import.meta !== 'undefined' && import.meta.env?.VITE_CATALOG_BASE_URL) || '');
      RemoteCatalogService.instance = new RemoteCatalogService(url);
    }
    return RemoteCatalogService.instance;
  }

  public static resetInstance(): void {
    if (RemoteCatalogService.instance) {
      RemoteCatalogService.instance.destroy();
      RemoteCatalogService.instance = null;
    }
  }

  public static notifyCatalogDownloaded(): void {
    // 1. Dispatch custom event on window if in DOM
    const target = typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : null);
    if (target && typeof (target as any).dispatchEvent === 'function') {
      try {
        const event = typeof CustomEvent !== 'undefined'
          ? new CustomEvent(RemoteCatalogService.CATALOG_DOWNLOADED_EVENT)
          : { type: RemoteCatalogService.CATALOG_DOWNLOADED_EVENT };
        (target as any).dispatchEvent(event);
      } catch {}
    }

    // 2. Directly notify all registered active listeners
    RemoteCatalogService.listeners.forEach((listener) => {
      try {
        listener();
      } catch (err) {
        console.warn('[RemoteCatalogService] Error in download listener:', err);
      }
    });
  }

  private workerPromise: Promise<any> | null = null;
  private isUsingHttpFallback = false;
  private baseUrl: string;
  private catalogUrl: string;
  private metaUrl: string;
  private removeStaticListener: (() => void) | null = null;

  private onCatalogDownloadedHandler = () => {
    this.reset().catch((err) => {
      console.warn('[RemoteCatalogService] Error resetting worker after catalog download:', err);
    });
  };

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl.replace(/\/+$/, '');
    this.catalogUrl = this.baseUrl ? `${this.baseUrl}/catalog.sqlite` : '/catalog.sqlite';
    this.metaUrl = this.baseUrl ? `${this.baseUrl}/catalog_meta.json` : '/catalog_meta.json';

    this.removeStaticListener = RemoteCatalogService.onCatalogDownloaded(this.onCatalogDownloadedHandler);

    const target = typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : null);
    if (target && typeof (target as any).addEventListener === 'function') {
      try {
        (target as any).addEventListener(RemoteCatalogService.CATALOG_DOWNLOADED_EVENT, this.onCatalogDownloadedHandler);
      } catch {}
    }
  }

  get isHttpFallbackActive(): boolean {
    return this.isUsingHttpFallback;
  }

  public async reset(): Promise<void> {
    const currentWorkerPromise = this.workerPromise;
    this.workerPromise = null;
    this.isUsingHttpFallback = false;
    if (currentWorkerPromise) {
      try {
        const worker = await currentWorkerPromise;
        await worker('close', {});
      } catch (e) {
        // Ignore close error on reset
      }
    }
  }

  public destroy(): void {
    if (this.removeStaticListener) {
      this.removeStaticListener();
      this.removeStaticListener = null;
    }
    const target = typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : null);
    if (target && typeof (target as any).removeEventListener === 'function') {
      try {
        (target as any).removeEventListener(RemoteCatalogService.CATALOG_DOWNLOADED_EVENT, this.onCatalogDownloadedHandler);
      } catch {}
    }
    this.reset().catch(() => {});
  }

  private getWorker() {
    if (!this.workerPromise) {
      this.workerPromise = this.initializeWorker();
    }
    return this.workerPromise;
  }

  private async initializeWorker() {
    try {
      // 1. Ensure OPFS has been bootstrapped with system.sqlite if needed
      await DatabaseBootstrapper.ensureSystemCatalogOPFS().catch((err) => {
        console.warn('[RemoteCatalogService] ensureSystemCatalogOPFS notice:', err);
      });

      // 2. Create a raw SQLite worker (supports both OPFS and HTTP VFS)
      const worker = await createSQLiteThread({ 
        http: createHttpBackend({ maxPageSize: 4096 })
      });

      // 3. Attempt to mount the local OPFS database (catalog.sqlite)
      try {
        await worker('open', { filename: 'catalog.sqlite', vfs: 'opfs' });
        
        // 4. Query total count in local SQLite (ingredients + portions)
        const countRes = await worker('exec', { 
          sql: 'SELECT (SELECT count(*) FROM base_ingredients) + (SELECT count(*) FROM portions)', 
          rowMode: 'array' 
        } as any);
        const localTotal = (countRes as any)?.result?.resultRows?.[0]?.[0] || 0;
        
        // 5. Determine whether to use remote HTTP range requests:
        // App is local-first: condition to NOT use network is to have the full catalog downloaded locally.
        // If localTotal > SYSTEM_CATALOG_META.itemCount (the built-in catalog count generated at build-time),
        // we know the full external catalog was downloaded and is available locally in OPFS.
        // ZERO network calls needed!
        if (localTotal > SYSTEM_CATALOG_META.itemCount) {
          console.log(`[RemoteCatalogService] Full catalog hydrated locally (${localTotal} items > built-in ${SYSTEM_CATALOG_META.itemCount}). Zero network needed.`);
          this.isUsingHttpFallback = false;
          return worker;
        }

        const isOnline = typeof navigator === 'undefined' ? true : navigator.onLine;
        let shouldUseHttp = false;

        if (isOnline && this.baseUrl) {
          try {
            const metaRes = await fetch(this.metaUrl, { 
              cache: 'no-cache', 
              signal: typeof AbortSignal !== 'undefined' && 'timeout' in AbortSignal ? AbortSignal.timeout(3000) : undefined 
            });
            if (metaRes.ok) {
              const meta = await metaRes.json();
              const remoteItemCount = Number(meta?.itemCount);
              if (remoteItemCount && localTotal < remoteItemCount) {
                console.log(`[RemoteCatalogService] Local SQLite has ${localTotal} items, remote has ${remoteItemCount}. Using HTTP Range Requests while online.`);
                shouldUseHttp = true;
              } else {
                console.log(`[RemoteCatalogService] Full catalog hydrated locally (${localTotal} items). Zero network needed.`);
              }
            }
          } catch {
            console.log('[RemoteCatalogService] Remote catalog metadata unreachable. Using local OPFS catalog.');
          }
        }

        if (shouldUseHttp) {
          this.isUsingHttpFallback = true;
          await worker('close', {});
        } else {
          this.isUsingHttpFallback = false;
        }
      } catch (err) {
        console.warn('[RemoteCatalogService] Failed to mount OPFS catalog, falling back to HTTP:', err);
        this.isUsingHttpFallback = true;
      }

      if (this.isUsingHttpFallback) {
        // Fallback to HTTP Range Request VFS pointing to R2 URL
        await worker('open', { filename: this.catalogUrl, vfs: 'http' });
      }

      return worker;
    } catch (err) {
      this.workerPromise = null;
      throw err;
    }
  }

  async searchIngredients(query: string, limit: number = 20): Promise<BaseIngredient[]> {
    const worker = await this.getWorker();
    const sanitizedQuery = query.replace(/[^\w\s\u00C0-\u017F]/g, '');
    const matchQuery = sanitizedQuery.split(/\s+/).filter(Boolean).map(term => term + '*').join(' ');
    
    if (!matchQuery) return [];

    const matchCondition = this.isUsingHttpFallback 
      ? `WHERE name LIKE '%${sanitizedQuery.replace(/'/g, "''")}%'`
      : `JOIN base_ingredients_fts f ON b.id = f.id WHERE f.base_ingredients_fts MATCH '${matchQuery.replace(/'/g, "''")}'`;

    const sql = `
      SELECT 
        b.id as id,
        b.name as name,
        b.source as source,
        b.lang as lang,
        b.calories_100g as calories_100g,
        b.protein_100g as protein_100g,
        b.carbs_100g as carbs_100g,
        b.fats_100g as fats_100g,
        b.contentHash as contentHash
      FROM base_ingredients b
      ${matchCondition}
      LIMIT ${limit}
    `;
    
    const results = await Promise.race([
      worker('exec', { sql, rowMode: 'array' } as any),
      new Promise<any>((_, reject) => setTimeout(() => reject(new Error('Remote search timeout')), 15000))
    ]).catch(async (err) => {
      console.error('Remote search error:', err);
      this.workerPromise = null;
      try { await worker('close', {}); } catch(e) {}

      // Fallback: If HTTP search failed (e.g. offline during session), try searching local OPFS
      if (this.isUsingHttpFallback) {
        try {
          const fallbackWorker = await createSQLiteThread({ http: createHttpBackend({ maxPageSize: 4096 }) });
          await fallbackWorker('open', { filename: 'catalog.sqlite', vfs: 'opfs' });
          const localSql = `
            SELECT b.id, b.name, b.source, b.lang, b.calories_100g, b.protein_100g, b.carbs_100g, b.fats_100g, b.contentHash
            FROM base_ingredients b
            JOIN base_ingredients_fts f ON b.id = f.id WHERE f.base_ingredients_fts MATCH '${matchQuery.replace(/'/g, "''")}'
            LIMIT ${limit}
          `;
          const localRes = await fallbackWorker('exec', { sql: localSql, rowMode: 'array' } as any);
          await fallbackWorker('close', {});
          return localRes;
        } catch {
          // Ignore fallback error
        }
      }
      return { result: { resultRows: [] } };
    });
    
    if (!results || !results.result || !results.result.resultRows || results.result.resultRows.length === 0) return [];
    
    return results.result.resultRows.map((vals: any) => ({
      id: vals[0],
      name: vals[1],
      source: vals[2],
      lang: vals[3],
      calories_100g: vals[4],
      protein_100g: vals[5],
      carbs_100g: vals[6],
      fats_100g: vals[7],
      contentHash: vals[8]
    })) as BaseIngredient[];
  }

  async getPortionsForIngredient(baseFoodId: string): Promise<Portion[]> {
    const worker = await this.getWorker();
    const sql = `
      SELECT 
        id as id,
        base_food_id as base_food_id,
        name as name,
        equivalent_weight_g as equivalent_weight_g,
        contentHash as contentHash
      FROM portions 
      WHERE base_food_id = '${baseFoodId.replace(/'/g, "''")}'
    `;
    
    const results = await Promise.race([
      worker('exec', { sql, rowMode: 'array' } as any),
      new Promise<any>((_, reject) => setTimeout(() => reject(new Error('Remote search timeout')), 10000))
    ]).catch(async (err) => {
      console.error('Remote portions error:', err);
      this.workerPromise = null;
      try { await worker('close', {}); } catch(e) {}

      // Fallback: If HTTP search failed, try local OPFS
      if (this.isUsingHttpFallback) {
        try {
          const fallbackWorker = await createSQLiteThread({ http: createHttpBackend({ maxPageSize: 4096 }) });
          await fallbackWorker('open', { filename: 'catalog.sqlite', vfs: 'opfs' });
          const localRes = await fallbackWorker('exec', { sql, rowMode: 'array' } as any);
          await fallbackWorker('close', {});
          return localRes;
        } catch {
          // Ignore
        }
      }
      return { result: { resultRows: [] } };
    });
    
    if (!results || !results.result || !results.result.resultRows || results.result.resultRows.length === 0) return [];
    
    return results.result.resultRows.map((vals: any) => ({
      id: vals[0],
      base_food_id: vals[1],
      name: vals[2],
      equivalent_weight_g: vals[3],
      contentHash: vals[4]
    })) as Portion[];
  }
}
